apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-python-basic-0qcv
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/qijing/release-e2e-pyxis-tenant/appstudio/devfile-sample-python-basic-0qcv@sha256:fa30d5d288857d2038198be1910aeeae6e805bf26f2c9fdf456afc02dac0b85a
        name: container-image
        resources: {}
status: {}
